apiVersion: v1
kind: Pod
metadata:
  name: url-shortener-pod
  labels:
    app: url-shortener
    type: service
spec:
  containers:
    - name: url-shortener
      image: url-shortener:v1 
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
