apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  type: NodePort
  ports:
    - name: "url-shortener"
      port: 8000
      targetPort: 8000
      nodePort: 31000
  selector:
    app: url-shortener
